name: Deploy Dumi to GitHub Pages

on:
  push:
    branches:
      - main  # 当你推送到 main 分支时触发
  workflow_dispatch: # 支持手动触发
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 设置 Node.js 版本，根据需要调整

      - name: Install dependencies
        run: |
          npm install -g dumi
          npm install

      - name: Build Dumi site
        run: npm run dumi:build # 如果你使用的是默认配置，这将构建到 dist/ 目录

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dumi-dist
          path: ./dist  # 上传 dist 目录

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages  # 创建一个新的 gh-pages 分支
          git rm -rf .  # 删除现有文件
          cp -r dist/* .  # 将构建的内容复制到根目录
          git add .  # 添加到 Git
          git commit -m "Deploy Dumi site"
          git push origin gh-pages --force  # 强制推送到 gh-pages 分支
